DEFAULT_QA_TEMPLATE_CATEGORIES = [
    {"id": "work-report", "name": "工作汇报", "enabled": True},
    {"id": "plan", "name": "方案策划", "enabled": True},
    {"id": "research-report", "name": "研究报告", "enabled": True},
    {"id": "official-document", "name": "政务公文", "enabled": True},
]

DEFAULT_QA_TEMPLATES = [
    {
        "id": "thought-report",
        "name": "思想汇报",
        "desc": "深度反思梳理，提升理论联系实际能力",
        "category_id": "official-document",
        "prompt": "请帮我起草一份思想汇报，要求结构规范、表达稳重，并结合实际工作认识。",
        "icon": "ScrollText",
        "color": "#10b981",
        "bg": "#ecfdf5",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "experience-note",
        "name": "心得体会",
        "desc": "提炼归纳感悟，形成规范心得文稿",
        "category_id": "work-report",
        "prompt": "请帮我写一份心得体会，突出学习收获、实践启发和后续改进方向。",
        "icon": "BriefcaseBusiness",
        "color": "#8b5cf6",
        "bg": "#f5f3ff",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "work-plan",
        "name": "工作计划",
        "desc": "明确目标方向，生成执行路线图",
        "category_id": "plan",
        "prompt": "请帮我制定一份工作计划，包含目标、重点任务、时间节点、责任分工和风险保障。",
        "icon": "Layers3",
        "color": "#f97316",
        "bg": "#fff7ed",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "debriefing-report",
        "name": "述职报告",
        "desc": "回顾履职成效，展现专业岗位贡献",
        "category_id": "work-report",
        "prompt": "请帮我写一份述职报告，围绕岗位职责、履职成效、能力提升和不足改进展开。",
        "icon": "BriefcaseBusiness",
        "color": "#f43f5e",
        "bg": "#fff1f2",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "office-writing",
        "name": "办公材料撰写",
        "desc": "多场景办公材料智能生成",
        "category_id": "official-document",
        "prompt": "请帮我撰写一份办公材料，要求条理清晰、语言规范，适合企业内部流转。",
        "icon": "PenLine",
        "color": "#3b82f6",
        "bg": "#eff6ff",
        "enabled": True,
        "show_on_home": True,
    },
    {
        "id": "project-impl-plan",
        "name": "项目实施方案",
        "desc": "明确路径、责任与节点，保障项目落地",
        "category_id": "plan",
        "prompt": "请帮我生成项目实施方案，包含背景目标、实施路径、组织分工、里程碑和保障措施。",
        "icon": "Layers3",
        "color": "#10b981",
        "bg": "#ecfdf5",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "work-push-plan",
        "name": "工作推进方案",
        "desc": "压实责任分工，推动任务高效完成",
        "category_id": "plan",
        "prompt": "请帮我写一份工作推进方案，重点说明任务拆解、推进机制、责任分工和验收标准。",
        "icon": "Layers3",
        "color": "#8b5cf6",
        "bg": "#f5f3ff",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "special-action-plan",
        "name": "专项行动方案",
        "desc": "集中资源攻坚，形成阶段性突破",
        "category_id": "plan",
        "prompt": "请帮我起草专项行动方案，要求目标明确、措施具体、节奏清晰、风险可控。",
        "icon": "Layers3",
        "color": "#f97316",
        "bg": "#fff7ed",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "ops-plan",
        "name": "运营策划方案",
        "desc": "提升运营效率，驱动业务增长",
        "category_id": "plan",
        "prompt": "请帮我写一份运营策划方案，包含用户洞察、运营目标、活动机制和数据复盘。",
        "icon": "Layers3",
        "color": "#f43f5e",
        "bg": "#fff1f2",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "topic-research-report",
        "name": "课题研究报告",
        "desc": "结构化呈现成果，提升学术规范",
        "category_id": "research-report",
        "prompt": "请帮我生成课题研究报告大纲，并围绕研究背景、方法、发现和建议展开正文。",
        "icon": "FileText",
        "color": "#3b82f6",
        "bg": "#eff6ff",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "tech-whitepaper",
        "name": "技术白皮书",
        "desc": "解析技术逻辑，建立行业专业标准",
        "category_id": "research-report",
        "prompt": "请帮我写一份技术白皮书，说明技术背景、架构设计、关键能力、应用价值和落地路径。",
        "icon": "FileText",
        "color": "#10b981",
        "bg": "#ecfdf5",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "product-prd",
        "name": "产品需求说明书",
        "desc": "逻辑清晰无歧义，直接对接研发",
        "category_id": "research-report",
        "prompt": "请帮我写一份产品需求说明书，包含背景、用户场景、功能需求、非功能需求和验收标准。",
        "icon": "FileText",
        "color": "#8b5cf6",
        "bg": "#f5f3ff",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "talent-dev-report",
        "name": "人才培养发展报告",
        "desc": "体系化培育员工，提升组织核心能力",
        "category_id": "research-report",
        "prompt": "请帮我写一份人才培养发展报告，分析现状、问题、培养体系和阶段性推进建议。",
        "icon": "FileText",
        "color": "#f97316",
        "bg": "#fff7ed",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "party-speech",
        "name": "党建专题讲话",
        "desc": "强化政治引领，输出高站位讲话稿",
        "category_id": "official-document",
        "prompt": "请帮我起草一份党建专题讲话稿，要求主题鲜明、结构稳健、语言庄重。",
        "icon": "ScrollText",
        "color": "#f43f5e",
        "bg": "#fff1f2",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "gov-summary",
        "name": "政务工作总结",
        "desc": "数据支撑、成效凝练，生成规范总结",
        "category_id": "official-document",
        "prompt": "请帮我写一份政务工作总结，突出主要做法、工作成效、存在问题和下一步安排。",
        "icon": "ScrollText",
        "color": "#3b82f6",
        "bg": "#eff6ff",
        "enabled": True,
        "show_on_home": False,
    },
    {
        "id": "hero-semantic-search",
        "name": "语义搜索",
        "desc": "面向知识库的语义检索与要点汇总",
        "category_id": "research-report",
        "prompt": "请基于知识库进行语义搜索，汇总与该主题相关的核心资料、关键观点和引用来源。",
        "icon": "Search",
        "color": "#10b981",
        "bg": "#ecfdf5",
        "enabled": True,
        "show_on_home": True,
    },
    {
        "id": "hero-open-qa",
        "name": "智能问答",
        "desc": "结合知识库的开放式问答",
        "category_id": "research-report",
        "prompt": "请结合知识库回答我的问题，并给出依据、引用来源和可执行建议。",
        "icon": "MessageSquare",
        "color": "#8b5cf6",
        "bg": "#f5f3ff",
        "enabled": True,
        "show_on_home": True,
    },
    {
        "id": "hero-doc-translate",
        "name": "文档翻译",
        "desc": "多语言文档翻译辅助",
        "category_id": "research-report",
        "prompt": "请将下列文本或段落翻译为[目标语言，如：英文]，保持术语与公文风格一致，专有名词首次出现可附原文括号备注。\n\n【原文】\n[粘贴待译内容]",
        "icon": "Globe",
        "color": "#f97316",
        "bg": "#fff7ed",
        "enabled": True,
        "show_on_home": True,
    },
]


DEFAULT_PORTAL_CONFIG = {
    "domains": [
        {"name": "营销", "space_ids": [], "color": "#d97706", "bg": "#fef3c7", "icon": "CheckCircle", "background_image": "/domain-covers/marketing.png", "enabled": True, "code": "SD"},
        {"name": "财务", "space_ids": [], "color": "#2563eb", "bg": "#eff6ff", "icon": "Settings", "background_image": "/domain-covers/finance.png", "enabled": True, "code": "FI"},
        {"name": "设备", "space_ids": [], "color": "#2563eb", "bg": "#eff6ff", "icon": "Settings", "background_image": "/domain-covers/equipment.png", "enabled": True, "code": "PM"},
        {"name": "安全", "space_ids": [], "color": "#dc2626", "bg": "#fee2e2", "icon": "Shield", "background_image": "/domain-covers/safety.png", "enabled": True, "code": "SA"},
        {"name": "环保", "space_ids": [], "color": "#16a34a", "bg": "#dcfce7", "icon": "Leaf", "background_image": "/domain-covers/environment.png", "enabled": True, "code": "EN"},
        {"name": "人力", "space_ids": [], "color": "#be185d", "bg": "#fce7f3", "icon": "GraduationCap", "background_image": "/domain-covers/hr.png", "enabled": True, "code": "HR"},
        {"name": "信息", "space_ids": [], "color": "#6366f1", "bg": "#ede9fe", "icon": "Network", "background_image": "/domain-covers/it.png", "enabled": True, "code": "IT"},
        {"name": "能源", "space_ids": [], "color": "#d97706", "bg": "#fef3c7", "icon": "Zap", "background_image": "/domain-covers/energy.png", "enabled": True, "code": "EM"},
        {"name": "质量", "space_ids": [], "color": "#7c3aed", "bg": "#f5f3ff", "icon": "CheckCircle", "background_image": "/domain-covers/quality.png", "enabled": True, "code": "QM"},
        {"name": "管理", "space_ids": [], "color": "#475569", "bg": "#e2e8f0", "icon": "Settings", "background_image": "/domain-covers/management.png", "enabled": True, "code": "AD"},
    ],
    "sections": [
        {
            "title": "知识推荐 · 最新精选",
            "tag": "最新精选",
            "link": "/list?tag=最新精选",
            "icon": "Star",
            "color": "#2563eb",
            "bg": "#eff6ff",
            "enabled": True,
        },
        {
            "title": "典型案例 · 事故分析",
            "tag": "典型案例",
            "link": "/list?tag=典型案例",
            "icon": "AlertTriangle",
            "color": "#dc2626",
            "bg": "#fee2e2",
            "enabled": True,
        },
    ],
    "qa": {
        "welcome_message": "你好，我是首钢股份知库智能助手，请问有什么可以帮您？",
        "hot_questions": [
            "振动纹通常如何排查？",
            "热轧精轧机轴承维护周期是多久？",
            "冷轧板面缺陷有哪些常见类型？",
            "高炉煤气利用率如何提升？",
            "安全巡检标准操作流程是什么？",
        ],
        "ai_search_system_prompt": "你是首钢知识门户的 AI 搜索助手。请基于知识空间检索结果，用简洁、专业、面向工程实践的中文总结答案。优先提炼结论、关键原因、处理步骤和适用范围；如果证据不足，明确说明信息不足，不要编造。",
        "qa_system_prompt": "你是首钢知识门户的技术问答助手。请结合知识库内容，用准确、克制、可执行的中文回答问题。优先给出结论、依据、操作建议和风险提示；若知识库中没有足够依据，请明确说明并建议进一步核实。",
        "quick_mode_system_prompt": "你是首钢知识门户的快速问答助手。请优先给出简洁结论，结合知识库依据回答，控制篇幅，避免展开无关背景；如果依据不足，请明确说明。",
        "normal_mode_system_prompt": "你是首钢知识门户的专业问答助手。请结合知识库内容，用准确、克制、可执行的中文回答问题。优先给出结论、依据、操作建议和风险提示；若知识库中没有足够依据，请明确说明并建议进一步核实。",
        "expert_mode_system_prompt": "你是首钢知识门户的专家问答助手。请基于知识库和推理能力分析复杂问题，按背景、判断依据、关键步骤、风险边界和建议方案组织回答；不要编造知识库中没有依据的事实。",
        "selected_model": "",
        "general_model": "",
        "reasoning_model": "",
        "template_categories": DEFAULT_QA_TEMPLATE_CATEGORIES,
        "templates": DEFAULT_QA_TEMPLATES,
    },
    "search": {
        "rerank_model_id": "",
    },
    "agent_config": {
        "categories": [],
        "agents": [],
    },
    "recommendation": {
        "provider": "tag_feed",
        "home_strategy": "tag+updated_at",
        "detail_strategy": "shared_tags+updated_at",
    },
    "display": {
        "home": {
            "section_page_size": 6,
            "hot_tags_count": 8,
            "qa_hot_count": 4,
            "domain_count": 10,
            "spaces_count": 6,
            "apps_count": 6,
        },
        "list": {
            "page_size": 10,
            "visible_tag_count": 2,
        },
        "search": {
            "page_size": 10,
            "visible_tag_count": 2,
        },
        "detail": {
            "related_files_count": 3,
            "visible_tag_count": 2,
        },
    },
    "apps": [
        {
            "id": 1,
            "name": "写作助手",
            "icon": "PenLine",
            "desc": "智能写作辅助工具，快速生成技术文档",
            "color": "#2563eb",
            "bg": "#eff6ff",
            "url": "",
            "enabled": True,
        },
        {
            "id": 2,
            "name": "语义搜索",
            "icon": "Search",
            "desc": "精准检索语义匹配，深度挖掘知识",
            "color": "#059669",
            "bg": "#d1fae5",
            "url": "",
            "enabled": True,
        },
        {
            "id": 3,
            "name": "智能问答",
            "icon": "MessageSquare",
            "desc": "知识问答即时回答，AI 驱动",
            "color": "#7c3aed",
            "bg": "#f5f3ff",
            "url": "",
            "enabled": True,
        },
        {
            "id": 4,
            "name": "文档翻译",
            "icon": "Globe",
            "desc": "多语翻译文档互译，支持主流语种",
            "color": "#d97706",
            "bg": "#fef3c7",
            "url": "",
            "enabled": True,
        },
        {
            "id": 5,
            "name": "报告生成",
            "icon": "BarChart3",
            "desc": "自动汇总分析数据，生成专业报告",
            "color": "#dc2626",
            "bg": "#fee2e2",
            "url": "",
            "enabled": True,
        },
        {
            "id": 6,
            "name": "知识图谱",
            "icon": "Network",
            "desc": "可视化知识关联，发现隐性关系",
            "color": "#0891b2",
            "bg": "#cffafe",
            "url": "",
            "enabled": True,
        },
    ],
    "banners": [
        {
            "id": 1,
            "label": "平台概览",
            "title": "首钢股份知库 — 钢铁行业知识共享平台",
            "desc": "汇聚设备、轧线、冷轧、能源全域知识，助力技术传承与创新",
            "image_url": "/banner-hero-1.jpg",
            "link_url": "",
            "enabled": True,
        },
        {
            "id": 2,
            "label": "专题推荐",
            "title": "典型案例·事故分析专题上线",
            "desc": "从实践中学习，从案例中成长，构建安全生产知识体系",
            "image_url": "/banner-hero-2.jpg",
            "link_url": "",
            "enabled": True,
        },
        {
            "id": 3,
            "label": "能力升级",
            "title": "技术问答全新升级",
            "desc": "AI 驱动的智能问答系统，快速定位知识、精准解答技术难题",
            "image_url": "/banner-hero-3.jpg",
            "link_url": "",
            "enabled": True,
        },
    ],
    "integrations": {
        "bisheng_admin_entry_url": "",
        "bisheng_knowledge_entry_url": "",
    },
    "site": {
        "header_brand_name": "首钢股份知库",
        "header_logo_url": "/site-logo-new.png",
        "login_brand_name": "首钢股份知库",
        "login_logo_url": "/shougang-stock-logo.png",
        "browser_title": "首钢股份知库",
        "favicon_url": "/site-favicon-horizontal-v2.png",
        "domain_count_cache_ttl_seconds": 43200,
    },
}
