DEFAULT_PORTAL_CONFIG = {
    "spaces": [],
    "domains": [
        {"name": "营销", "space_ids": [], "color": "#d97706", "bg": "#fef3c7", "icon": "CheckCircle", "background_image": "/domain-covers/marketing.png", "enabled": True},
        {"name": "财务", "space_ids": [], "color": "#2563eb", "bg": "#eff6ff", "icon": "Settings", "background_image": "/domain-covers/finance.png", "enabled": True},
        {"name": "设备", "space_ids": [], "color": "#2563eb", "bg": "#eff6ff", "icon": "Settings", "background_image": "/domain-covers/equipment.png", "enabled": True},
        {"name": "安全", "space_ids": [], "color": "#dc2626", "bg": "#fee2e2", "icon": "Shield", "background_image": "/domain-covers/safety.png", "enabled": True},
        {"name": "环保", "space_ids": [], "color": "#16a34a", "bg": "#dcfce7", "icon": "Leaf", "background_image": "/domain-covers/environment.png", "enabled": True},
        {"name": "人力", "space_ids": [], "color": "#be185d", "bg": "#fce7f3", "icon": "GraduationCap", "background_image": "/domain-covers/hr.png", "enabled": True},
        {"name": "信息", "space_ids": [], "color": "#6366f1", "bg": "#ede9fe", "icon": "Network", "background_image": "/domain-covers/it.png", "enabled": True},
        {"name": "能源", "space_ids": [], "color": "#d97706", "bg": "#fef3c7", "icon": "Zap", "background_image": "/domain-covers/energy.png", "enabled": True},
        {"name": "质量", "space_ids": [], "color": "#7c3aed", "bg": "#f5f3ff", "icon": "CheckCircle", "background_image": "/domain-covers/quality.png", "enabled": True},
        {"name": "管理", "space_ids": [], "color": "#475569", "bg": "#e2e8f0", "icon": "Settings", "background_image": "/domain-covers/management.png", "enabled": True},
    ],
    "sections": [
        {
            "title": "知识推荐 · 最新精选",
            "tag": "最新精选",
            "link": "/list?tag=最新精选",
            "icon": "Star",
            "color": "#2563eb",
            "bg": "#eff6ff",
            "enabled": True,
        },
        {
            "title": "典型案例 · 事故分析",
            "tag": "典型案例",
            "link": "/list?tag=典型案例",
            "icon": "AlertTriangle",
            "color": "#dc2626",
            "bg": "#fee2e2",
            "enabled": True,
        },
    ],
    "qa": {
        "knowledge_space_ids": [],
        "welcome_message": "你好，我是首钢股份知库智能助手，请问有什么可以帮您？",
        "hot_questions": [
            "振动纹通常如何排查？",
            "热轧精轧机轴承维护周期是多久？",
            "冷轧板面缺陷有哪些常见类型？",
            "高炉煤气利用率如何提升？",
            "安全巡检标准操作流程是什么？",
        ],
        "ai_search_system_prompt": "你是首钢知识门户的 AI 搜索助手。请基于知识空间检索结果，用简洁、专业、面向工程实践的中文总结答案。优先提炼结论、关键原因、处理步骤和适用范围；如果证据不足，明确说明信息不足，不要编造。",
        "qa_system_prompt": "你是首钢知识门户的技术问答助手。请结合知识库内容，用准确、克制、可执行的中文回答问题。优先给出结论、依据、操作建议和风险提示；若知识库中没有足够依据，请明确说明并建议进一步核实。",
        "selected_model": "",
    },
    "recommendation": {
        "provider": "tag_feed",
        "home_strategy": "tag+updated_at",
        "detail_strategy": "shared_tags+updated_at",
    },
    "display": {
        "home": {
            "section_page_size": 6,
            "hot_tags_count": 8,
            "qa_hot_count": 4,
            "domain_count": 10,
            "spaces_count": 6,
            "apps_count": 6,
        },
        "list": {
            "page_size": 10,
            "visible_tag_count": 2,
        },
        "search": {
            "page_size": 10,
            "visible_tag_count": 2,
        },
        "detail": {
            "related_files_count": 3,
            "visible_tag_count": 2,
        },
    },
    "apps": [
        {
            "id": 1,
            "name": "写作助手",
            "icon": "PenLine",
            "desc": "智能写作辅助工具，快速生成技术文档",
            "color": "#2563eb",
            "bg": "#eff6ff",
            "url": "",
            "enabled": True,
        },
        {
            "id": 2,
            "name": "语义搜索",
            "icon": "Search",
            "desc": "精准检索语义匹配，深度挖掘知识",
            "color": "#059669",
            "bg": "#d1fae5",
            "url": "",
            "enabled": True,
        },
        {
            "id": 3,
            "name": "智能问答",
            "icon": "MessageSquare",
            "desc": "知识问答即时回答，AI 驱动",
            "color": "#7c3aed",
            "bg": "#f5f3ff",
            "url": "",
            "enabled": True,
        },
        {
            "id": 4,
            "name": "文档翻译",
            "icon": "Globe",
            "desc": "多语翻译文档互译，支持主流语种",
            "color": "#d97706",
            "bg": "#fef3c7",
            "url": "",
            "enabled": True,
        },
        {
            "id": 5,
            "name": "报告生成",
            "icon": "BarChart3",
            "desc": "自动汇总分析数据，生成专业报告",
            "color": "#dc2626",
            "bg": "#fee2e2",
            "url": "",
            "enabled": True,
        },
        {
            "id": 6,
            "name": "知识图谱",
            "icon": "Network",
            "desc": "可视化知识关联，发现隐性关系",
            "color": "#0891b2",
            "bg": "#cffafe",
            "url": "",
            "enabled": True,
        },
    ],
    "banners": [
        {
            "id": 1,
            "label": "平台概览",
            "title": "首钢股份知库 — 钢铁行业知识共享平台",
            "desc": "汇聚设备、轧线、冷轧、能源全域知识，助力技术传承与创新",
            "image_url": "/banner-hero-1.jpg",
            "link_url": "",
            "enabled": True,
        },
        {
            "id": 2,
            "label": "专题推荐",
            "title": "典型案例·事故分析专题上线",
            "desc": "从实践中学习，从案例中成长，构建安全生产知识体系",
            "image_url": "/banner-hero-2.jpg",
            "link_url": "",
            "enabled": True,
        },
        {
            "id": 3,
            "label": "能力升级",
            "title": "技术问答全新升级",
            "desc": "AI 驱动的智能问答系统，快速定位知识、精准解答技术难题",
            "image_url": "/banner-hero-3.jpg",
            "link_url": "",
            "enabled": True,
        },
    ],
    "integrations": {
        "bisheng_admin_entry_url": "",
        "bisheng_knowledge_entry_url": "",
    },
    "site": {
        "header_brand_name": "首钢股份知库",
        "header_logo_url": "/site-logo-new.png",
        "login_brand_name": "首钢股份知库",
        "login_logo_url": "/shougang-stock-logo.png",
        "browser_title": "首钢股份知库",
        "favicon_url": "/favicon.svg",
    },
}
